# Generated by Django 3.1.2 on 2020-10-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=264)),
                ('lastname', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
            ],
        ),
    ]
